const express = require('express')
const router = express.Router()
const controller = require('../controllers/adminControllers')
const storage = require('../Midlewares/multer')
const bannerstorage =require('../Midlewares/bannermulter')

router.get('/product',controller.productList)
router.get('/error',controller.adminError)
router.route('/addproduct')
       .get(controller.viewProduct)
       .post(storage.array('image',3),controller.addProduct)
router.get('/user',controller.userList) 
router.route('/editproduct/:id')
       .get(controller.editProduct)
       .post(storage.array('images',3),controller.postEditProduct)
router.get('/deleteProduct/:id',controller.deleteProduct)  
router.get('/blockUser/:id',controller.blockUser)     
router.get('/unblockUser/:id',controller.unblockUser) 
router.route('/category')
       .get(controller.addCategory)
       .post(controller.postCategory)
router.route('/viewType')
       .get(controller.addviewType)
       .post(controller.postviewType)
router.get('/',controller.dashboard)    
router.get('/categoryList',controller.categoryList)
router.get('/deletecategory/:id',controller.deletecategory) 
router.get('/viewTypeList',controller.viewTypeList)
router.get('/deleteviewType/:id',controller.deleteviewType) 
router.route('/addbanner')
       .get(controller.addbanner)
       .post(bannerstorage.single ("bannerimage"),controller.postaddbanner)
router.get('/bannerList',controller.bannerList)
router.route('/editbanner/:id')
      .get(controller.editBanner)
      .post(bannerstorage.single ("bannerimage"),controller.posteditBanner)
router.get('/deletebanner/:id',controller.deletebanner) 
router.get('/adminlogin',controller.adminlogin)

module.exports = router;